// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BuySharesReducer from "../buy_shares_reducer";
import ClaimPayoutReducer from "../claim_payout_reducer";
import CreateMarketReducer from "../create_market_reducer";
import MarkMarketResolvedReducer from "../mark_market_resolved_reducer";
import RegisterUserReducer from "../register_user_reducer";
import SellSharesReducer from "../sell_shares_reducer";

export type BuySharesParams = __Infer<typeof BuySharesReducer>;
export type ClaimPayoutParams = __Infer<typeof ClaimPayoutReducer>;
export type CreateMarketParams = __Infer<typeof CreateMarketReducer>;
export type MarkMarketResolvedParams = __Infer<typeof MarkMarketResolvedReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type SellSharesParams = __Infer<typeof SellSharesReducer>;

