// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  marketId: __t.u64().primaryKey().name("market_id"),
  lastPrice: __t.u32().name("last_price"),
  totalVolume: __t.u64().name("total_volume"),
  openInterest: __t.u64().name("open_interest"),
  updatedAt: __t.timestamp().name("updated_at"),
});
