// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Outcome,
  MarketStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  question: __t.string(),
  description: __t.string(),
  get status() {
    return MarketStatus;
  },
  closeTime: __t.timestamp().name("close_time"),
  resolveTime: __t.option(__t.timestamp()).name("resolve_time"),
  get resolution() {
    return __t.option(Outcome);
  },
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  yesReserves: __t.i64().name("yes_reserves"),
  noReserves: __t.i64().name("no_reserves"),
  invariantK: __t.i128().name("invariant_k"),
  collateral: __t.i64(),
});
