// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Outcome,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  userId: __t.identity().name("user_id"),
  marketId: __t.u64().name("market_id"),
  get outcome() {
    return Outcome;
  },
  shares: __t.i64(),
  averagePrice: __t.u32().name("average_price"),
  updatedAt: __t.timestamp().name("updated_at"),
});
