// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Outcome,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  marketId: __t.u64().name("market_id"),
  get outcome() {
    return Outcome;
  },
  price: __t.u32(),
  quantity: __t.i64(),
  buyerId: __t.identity().name("buyer_id"),
  sellerId: __t.identity().name("seller_id"),
  timestamp: __t.timestamp(),
});
