// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Admin = __t.object("Admin", {
  userId: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Admin = __Infer<typeof Admin>;

export const Balance = __t.object("Balance", {
  userId: __t.identity(),
  balance: __t.i64(),
  lockedBalance: __t.i64(),
  updatedAt: __t.timestamp(),
});
export type Balance = __Infer<typeof Balance>;

export const Market = __t.object("Market", {
  id: __t.u64(),
  question: __t.string(),
  description: __t.string(),
  get status() {
    return MarketStatus;
  },
  closeTime: __t.timestamp(),
  resolveTime: __t.option(__t.timestamp()),
  get resolution() {
    return __t.option(Outcome);
  },
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  yesReserves: __t.i64(),
  noReserves: __t.i64(),
  invariantK: __t.i128(),
  collateral: __t.i64(),
});
export type Market = __Infer<typeof Market>;

export const MarketStats = __t.object("MarketStats", {
  marketId: __t.u64(),
  lastPrice: __t.u32(),
  totalVolume: __t.u64(),
  openInterest: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type MarketStats = __Infer<typeof MarketStats>;

// The tagged union or sum type for the algebraic type `MarketStatus`.
export const MarketStatus = __t.enum("MarketStatus", {
  Open: __t.unit(),
  Resolved: __t.unit(),
});
export type MarketStatus = __Infer<typeof MarketStatus>;

// The tagged union or sum type for the algebraic type `Outcome`.
export const Outcome = __t.enum("Outcome", {
  Yes: __t.unit(),
  No: __t.unit(),
});
export type Outcome = __Infer<typeof Outcome>;

export const Position = __t.object("Position", {
  id: __t.u64(),
  userId: __t.identity(),
  marketId: __t.u64(),
  get outcome() {
    return Outcome;
  },
  shares: __t.i64(),
  averagePrice: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type Position = __Infer<typeof Position>;

export const PricePoint = __t.object("PricePoint", {
  id: __t.u64(),
  marketId: __t.u64(),
  get outcome() {
    return Outcome;
  },
  price: __t.u32(),
  volume: __t.u64(),
  timestamp: __t.timestamp(),
});
export type PricePoint = __Infer<typeof PricePoint>;

export const Trade = __t.object("Trade", {
  id: __t.u64(),
  marketId: __t.u64(),
  get outcome() {
    return Outcome;
  },
  price: __t.u32(),
  quantity: __t.i64(),
  buyerId: __t.identity(),
  sellerId: __t.identity(),
  timestamp: __t.timestamp(),
});
export type Trade = __Infer<typeof Trade>;

export const User = __t.object("User", {
  id: __t.identity(),
  username: __t.string(),
  createdAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const UserStats = __t.object("UserStats", {
  userId: __t.identity(),
  portfolioValue: __t.i64(),
  realizedPnl: __t.i64(),
  totalVolume: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type UserStats = __Infer<typeof UserStats>;

